# config.yaml

artifacts_dir: artifacts

data_ingestion:
  raw_data_path: data/house_Data.csv
  train_data_path: artifacts/train.csv
  test_data_path: artifacts/test.csv

data_cleaning:
  train_cleaned_path: artifacts/train_cleaned.csv
  test_cleaned_path: artifacts/test_cleaned.csv

data_transformation:
  preprocessor_path: artifacts/preprocessor/preprocessor.pkl

model_trainer:
  trained_model_path: artifacts/model.pkl

logger:
  log_dir: logs
